### ISSUE TITLE
Error in index.js when switching cosmetics

### ISSUE THREAD

**Issue by ghost** [ItsVops/CB-Cosmetics-API#3]
Hello,

I've noticed that I get this error when users try to switch cosmetics:

/root/comboclientapi/index.js:62
  file.cosmetics[cosmetic].active = body == "true";
                                  ^

TypeError: Cannot set property 'active' of undefined
    at /root/comboclientapi/index.js:62:35
    at Layer.handle [as handle_request] (/root/comboclientapi/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/comboclientapi/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/comboclientapi/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/comboclientapi/node_modules/express/lib/router/layer.js:95:5)
    at /root/comboclientapi/node_modules/express/lib/router/index.js:281:22
    at param (/root/comboclientapi/node_modules/express/lib/router/index.js:354:14)
    at param (/root/comboclientapi/node_modules/express/lib/router/index.js:365:14)
    at param (/root/comboclientapi/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/root/comboclientapi/node_modules/express/lib/router/index.js:410:3)

**Comment by vopswtf** [comment]
I’ll fix this tonight. It looks like the user switching cosmetics doesn’t
have cosmetics.
